---
hostname: gallery.example.com

# DigitalOcean droplet settings.
region: nyc3
size: 1gb
# Get a list of all images with:
#   curl -X GET --silent "https://api.digitalocean.com/v2/images?per_page=999" \
#   -H "Authorization: Bearer $DO_API_TOKEN"
image: ubuntu-16-04-x64

# SSH key details.
pubkey_name: My Public Key
pubkey_location: ~/.ssh/id_rsa.pub

# Admin account.
server_admin_username: drupal
security_sudoers_passwordless: ['{{ server_admin_username }}']

# Drupal deployment vars.
drupal_deploy: true
drupal_deploy_repo: https://github.com/geerlingguy/drupal-photo-gallery.git
drupal_deploy_version: master
drupal_deploy_update: true
drupal_deploy_dir: /var/www/drupal
drupal_deploy_accept_hostkey: yes
drupal_deploy_composer_install: yes
drupal_core_path: "{{ drupal_deploy_dir }}/docroot"
drupal_core_owner: "{{ server_admin_username }}"
drupal_db_user: gallery
drupal_db_password: add-a-secure-password-override
drupal_db_name: gallery
drupal_db_backend: mysql
drupal_db_host: "127.0.0.1"
drupal_composer_dependencies: []

# Drupal installation vars.
drupal_build_composer_project: no
drupal_install_profile: minimal
drupal_site_name: "Drupal Photo Gallery"
drupal_account_name: admin
drupal_account_pass: add-a-secure-password
drupal_site_install_extra_args:
  - "--config-dir=../config/sync"

# Firewall settings.
firewall_disable_ufw: yes
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# PHP settings.
php_version: "7.1"
php_packages_extra:
  - imagemagick
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-imagick"
php_memory_limit: "256M"
php_opcache_memory_consumption: "96"
php_upload_max_filesize: "128M"
php_max_file_uploads: "300"
php_post_max_size: "128M"
php_enable_php_fpm: no

# Apache settings.
apache_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-php{{ php_version }}
apache_vhosts:
  - servername: "{{ hostname }}"
    serveralias: "www.{{ hostname }}"
    serveradmin: webmaster@{{ hostname }}
    documentroot: "{{ drupal_core_path }}"
apache_create_vhosts: yes
apache_remove_default_vhost: yes
apache_mods_enabled:
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load

# MySQL settings.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# Other settings.
drush_version: "8.1.12"
exim_primary_hostname: "{{ hostname }}"

# Only to be used during initial provisioning or in case of weird emergency, for
# example if you get the error "Failed to connect to the host via ssh:
# ssh_exchange_identification: read: Connection reset by peer"
force_root_login: no
